### ISSUE TITLE
location dosnt work on ios8

### ISSUE THREAD

**Issue by syrakozz** [AmbientStatus/ASLocationMonitor#1]
what should i do plz help ,
any specific config

**Comment by ruddfawcett** [comment]
Hey @syrakozz, have you gotten it to work with iOS7?  I haven't put this control through much testing, so if you can verify you've gotten it to work on other iOS versions, it will help me pinpoint the problem.

**Comment by syrakozz** [comment]
yes it work on ios7

**Comment by ruddfawcett** [comment]
Hmmm.  I'll take a look at the differences between the location APIs on iOS7 and 8 if there are any.  I did notice that [ASTransitMonitor](https://github.com/AmbientStatus/ASTransitMonitor) wasn't working in June when I was running the iOS8 beta, so I had to downgrade when I was writing it to test it out.  

I'll be sure to get back to you when I have a solid/reliable solution.

**Comment by ruddfawcett** [comment]
@syrakozz this is quite an old issue, and I apologize for not getting back to you -- I have been very busy. I was wondering, however, if you have had success with this library recently, and, if so, with what iOS?

I am also going to close this issue as I plan on rewriting the lib.
